[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--html"]

[tasks.c]
alias = "cov"

[tasks.cov-open]
command = "cargo"
args = ["llvm-cov", "--open"]

[tasks.co]
alias = "cov-open"

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.t]
alias = "test"
